/**
 * @file  bsp_gpio.c
 * @brief GPIO init for STM32G030F6P6 (TSSOP20).
 *
 * PA2  USART2_TX AF1  debug
 * PA4  LED output
 * PA11 I2C2_SCL  AF6  SEN66
 * PA12 I2C2_SDA  AF6  SEN66
 * PB6  USART1_TX AF0  RS485
 * PB7  USART1_RX AF0  RS485
 */
#include "bsp/bsp_gpio.h"
#include "stm32g0xx.h"

#define PIN_MODE_AF(p)     (2UL << ((p) * 2U))
#define PIN_MODE_OUT(p)    (1UL << ((p) * 2U))
#define PIN_MODE_MASK(p)   (3UL << ((p) * 2U))
#define PIN_OT_OD(p)       (1UL << (p))
#define PIN_OSPEED_HIGH(p) (2UL << ((p) * 2U))
#define PIN_OSPEED_MASK(p) (3UL << ((p) * 2U))
#define PIN_PUPD_PU(p)     (1UL << ((p) * 2U))
#define PIN_PUPD_MASK(p)   (3UL << ((p) * 2U))
#define AFR_SET(p, af)     ((uint32_t)(af) << (((p) % 8U) * 4U))
#define AFR_MASK(p)        (0xFUL << (((p) % 8U) * 4U))

#define PIN_UART2_TX (2U)
#define PIN_UART2_RX (3U)
#define PIN_LED      (4U)
#define PIN_I2C_SCL  (11U)
#define PIN_I2C_SDA  (12U)
#define PIN_UART1_TX (6U)
#define PIN_UART1_RX (7U)

#define AF_I2C2   (6U)
#define AF_USART2 (1U)
#define AF_USART1 (0U)

void BSP_GPIO_Init(void)
{
    SET_BIT(RCC->IOPENR, RCC_IOPENR_GPIOAEN | RCC_IOPENR_GPIOBEN);
    (void)RCC->IOPENR;

    /* USART2 TX/RX — PA2/PA3, AF1, push-pull */
    GPIOA->MODER   &= ~(PIN_MODE_MASK(PIN_UART2_TX) | PIN_MODE_MASK(PIN_UART2_RX));
    GPIOA->MODER   |=  (PIN_MODE_AF(PIN_UART2_TX)   | PIN_MODE_AF(PIN_UART2_RX));
    GPIOA->OTYPER  &= ~(PIN_OT_OD(PIN_UART2_TX)     | PIN_OT_OD(PIN_UART2_RX));
    GPIOA->OSPEEDR &= ~(PIN_OSPEED_MASK(PIN_UART2_TX) | PIN_OSPEED_MASK(PIN_UART2_RX));
    GPIOA->OSPEEDR |=  (PIN_OSPEED_HIGH(PIN_UART2_TX) | PIN_OSPEED_HIGH(PIN_UART2_RX));
    GPIOA->PUPDR   &= ~(PIN_PUPD_MASK(PIN_UART2_TX) | PIN_PUPD_MASK(PIN_UART2_RX));
    GPIOA->PUPDR   |=   PIN_PUPD_PU(PIN_UART2_RX);
    GPIOA->AFR[0]  &= ~(AFR_MASK(PIN_UART2_TX) | AFR_MASK(PIN_UART2_RX));
    GPIOA->AFR[0]  |=  (AFR_SET(PIN_UART2_TX, AF_USART2) | AFR_SET(PIN_UART2_RX, AF_USART2));

    /* LED — PA4, push-pull output, start OFF */
    GPIOA->MODER  &= ~PIN_MODE_MASK(PIN_LED);
    GPIOA->MODER  |=  PIN_MODE_OUT(PIN_LED);
    GPIOA->OTYPER &= ~PIN_OT_OD(PIN_LED);
    GPIOA->ODR    &= ~(1UL << PIN_LED);

    /* I2C2 SCL/SDA — PA11/PA12, AF6, open-drain, pull-up */
    GPIOA->MODER   &= ~(PIN_MODE_MASK(PIN_I2C_SCL) | PIN_MODE_MASK(PIN_I2C_SDA));
    GPIOA->MODER   |=  (PIN_MODE_AF(PIN_I2C_SCL)   | PIN_MODE_AF(PIN_I2C_SDA));
    GPIOA->OTYPER  |=  (PIN_OT_OD(PIN_I2C_SCL)     | PIN_OT_OD(PIN_I2C_SDA));
    GPIOA->OSPEEDR &= ~(PIN_OSPEED_MASK(PIN_I2C_SCL) | PIN_OSPEED_MASK(PIN_I2C_SDA));
    GPIOA->OSPEEDR |=  (PIN_OSPEED_HIGH(PIN_I2C_SCL) | PIN_OSPEED_HIGH(PIN_I2C_SDA));
    GPIOA->PUPDR   &= ~(PIN_PUPD_MASK(PIN_I2C_SCL) | PIN_PUPD_MASK(PIN_I2C_SDA));
    GPIOA->PUPDR   |=  (PIN_PUPD_PU(PIN_I2C_SCL)   | PIN_PUPD_PU(PIN_I2C_SDA));
    GPIOA->AFR[1]  &= ~(AFR_MASK(PIN_I2C_SCL) | AFR_MASK(PIN_I2C_SDA));
    GPIOA->AFR[1]  |=  (AFR_SET(PIN_I2C_SCL, AF_I2C2) | AFR_SET(PIN_I2C_SDA, AF_I2C2));

    /* USART1 TX/RX — PB6/PB7, AF0, push-pull */
    GPIOB->MODER   &= ~(PIN_MODE_MASK(PIN_UART1_TX) | PIN_MODE_MASK(PIN_UART1_RX));
    GPIOB->MODER   |=  (PIN_MODE_AF(PIN_UART1_TX)   | PIN_MODE_AF(PIN_UART1_RX));
    GPIOB->OTYPER  &= ~(PIN_OT_OD(PIN_UART1_TX)     | PIN_OT_OD(PIN_UART1_RX));
    GPIOB->OSPEEDR &= ~(PIN_OSPEED_MASK(PIN_UART1_TX) | PIN_OSPEED_MASK(PIN_UART1_RX));
    GPIOB->OSPEEDR |=  (PIN_OSPEED_HIGH(PIN_UART1_TX) | PIN_OSPEED_HIGH(PIN_UART1_RX));
    GPIOB->PUPDR   &= ~(PIN_PUPD_MASK(PIN_UART1_TX) | PIN_PUPD_MASK(PIN_UART1_RX));
    GPIOB->PUPDR   |=   PIN_PUPD_PU(PIN_UART1_RX);
    GPIOB->AFR[0]  &= ~(AFR_MASK(PIN_UART1_TX) | AFR_MASK(PIN_UART1_RX));
    GPIOB->AFR[0]  |=  (AFR_SET(PIN_UART1_TX, AF_USART1) | AFR_SET(PIN_UART1_RX, AF_USART1));
}

void BSP_GPIO_LedOn(void)     { GPIOA->BSRR = (1UL << PIN_LED); }
void BSP_GPIO_LedOff(void)    { GPIOA->BSRR = (1UL << (PIN_LED + 16U)); }
void BSP_GPIO_LedToggle(void) { GPIOA->ODR  ^= (1UL << PIN_LED); }
